saved_keys: ['rgb_imgs', 'rgb_lit_imgs', 'normal_viz_imgs', 'irradiance_imgs']

relight_mode: 'hdri' # hdri or directional
ambient: [0.55] # for directional
intensity: 1.75 # exposure control in hri or light intensity in directional
hdri_path: './data/HDRis/tricolor_points.exr'
hdri_resolution: [32,64]
num_secondary_rays: 64
raychunk: 8192
forward_type: render_relight
floor_point: [0,0.9,0]
floor_normal: [0,-1,0]

render_dataset:
  _target_: run_render.HDRIDataset
  h5_path: data/RANA/${.subject}_train.h5
  subject: subject_01
  idxs: np.array([16]*72)
  angles: [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60, 65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355]
  #angles: [0, 45, 90, 135, 180, 225, 270, 315]
  resolution: [540, 960]
  cam_overwrite: -1 
  bkgd_to_use: white



model_config: ???
output_path: ???